// <auto-generated />
namespace CardValidation.Repository
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddCard : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddCard));
        
        string IMigrationMetadata.Id
        {
            get { return "201811241410429_AddCard"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
